### ISSUE TITLE
error: Unrecognized function or variable 'hanning'. 

### ISSUE THREAD

**Issue by hyeyeoun** [MariusKlug/zapline-plus#13]
Hi, 

entered this code in matlab prompt
`EEG = clean_data_with_zapline_plus_eeglab_wrapper(EEG,struct('noisefreqs','line'))
`
and I got an error message. 

```
Removing frequency artifacts using ZapLine with adaptations for automatic component selection and chunked data.
  
---------------- PLEASE CITE ------------------
 
Klug, M., & Kloosterman, N. A. (2022).Zapline-plus: A Zapline extension for automatic and adaptiveremoval of frequency-specific noise artifacts in M/EEG.
Human Brain Mapping,1–16. https://doi.org/10.1002/hbm.25832
 
-------------------- AND ---------------------
 
de Cheveigne, A. (2020) ZapLine: a simple and effective method to remove power line artifacts.
NeuroImage, 1, 1-13. https://doi.org/10.1016/j.neuroimage.2019.116356
 
------------------ THANKS! -------------------
 
 
 
Computing initial spectrum...
**Unrecognized function or variable 'hanning'.**

Error in clean_data_with_zapline_plus (line 295)
[pxx_raw_log,f]=pwelch(data,hanning(winSizeCompleteSpectrum*srate),[],[],srate);

Error in clean_data_with_zapline_plus_eeglab_wrapper (line 25)
    [EEG.data, EEG.etc.zapline.config, EEG.etc.zapline.analyticsResults,
    plothandles] = clean_data_with_zapline_plus(EEG.data, EEG.srate,
    zaplineConfig);
```
 
Since I just started to analyze EEG data and tried to follow several tutorials at the newbie level, I don't know where to start to fix it. Do I need an additional tool to solve "hanning()" problem above? I attached the sample eeg raw file I used.

[01_992_20221208_141653.mff.zip](https://github.com/MariusKlug/zapline-plus/files/10243257/01_992_20221208_141653.mff.zip)

**Comment by MariusKlug** [comment]
Hey, very sorry for not getting back sooner! This is a function that is present in the signal processing toolbox, which is a requirement when using zapline-plus. This is now specified in the readme, thanks for pointing out the question!
