### ISSUE TITLE
Potential Zapline Plus artifact. Not present with original Zapline.

### ISSUE THREAD

**Issue by malcolmudeozor** [MariusKlug/zapline-plus#19]
Hi! I just tried upgrading from your original ZapLine algorithm to ZapLine-plus.  After Zaplining the data using zapline-plus, I imported the cleaned data in Python and noticed what I believe is an artifact. For context, this is an hour and a half of 64-channel surface EMG data with a sampling rate of 2KHz. 

I ran `clean_data_with_zapline_plus(myData, myData.SamplingFrequency, 'noisefreqs', 'line', 'plotResults', 0)`.  The following image shows Power-Spectral Density (PSD) and Spectrogram Plots to help visualize the effect of the Zapline. On the PSD is a line for each channel; the Spectrogram represents all channels averaged together. 

![Zapline_plus](https://user-images.githubusercontent.com/65089056/235766639-720a8ac9-a52a-4305-b257-7c9b83d62c43.png)

Next is the result of using the Python implementation (Meegkit module) of your original Zapline algorithm, specifying a line frequency at 60Hz and the removal of 8 components (decided by trial and error). You will see from the plots that the artifact does not appear with this method. However, I am still keen on using Zapline-plus due to its autodetection. 

![Zapline_original](https://user-images.githubusercontent.com/65089056/235766739-f6513e7c-1606-46c7-8fc7-09ab67e11459.png)

I'm a bit new to using these tools and apologize if I haven't done some things correctly. 

Do you have any insight or advice? Thank you in advance for your help.

Best Malcolm

**Comment by MariusKlug** [comment]
Interesting, thanks for reporting. We do not recommend running Zapline-plus with high-frequency data, but downsampled to 250-500Hz. Perhaps that might solve the issue for you? But I understand that this may be an issue when doing EMG research...

You can start playing around with the different parameters, e.g. chunk length. The main difference that potentially introduces this artifact for you is the chunking. So you can start trying with larger chunks (e.g. 10 times larger than default) or even go as far as switching the chunking off entirely.

Hope this helps!

**Comment by malcolmudeozor** [comment]
Thanks for the advice! I'm going to try changing/removing the chunking. I'm not exactly sure how to adjust the chucking, however. The documentation states :

`chunkLength  - length of chunks to be cleaned in seconds. if set to 0, automatic chunks will be used. (default = 0)`
`segmentLength  - length of the segments for automatic chunk detection in seconds (default = 1)`
`minChunkLength   - minimum chunk length of automatic chunk detection in seconds (default = 30)`

Are you suggesting I increase the minChunkLength parameter? Also, I'm not sure how I would turn off the chunking using these parameters.

**Comment by MariusKlug** [comment]
So there are several options. First you can try using a higher `minChunkLength`. Then, if that does not work, you can use a fixed chunk length by setting `chunkLength` to a value in seconds, say, 120 or 180 or so in yur case perhaps. Then you can increase this further, or use a single chunk by setting `chunkLength` to 99999999.

Let me know how it goes!

**Comment by malcolmudeozor** [comment]
Hey Marius! Thanks so much for your help. I tried 10 min chunks and noticed an improvement, but I still had the artifact. Removing the chunking altogether was the best solution and gave me better results than the Zapline original algorithm. 

Here's the result of removing the chunking

![zapPlusNoChunking](https://github.com/MariusKlug/zapline-plus/assets/65089056/53febfad-ccfe-4d88-9c03-efd9ada413e8)

As you can see, there is still a little bit of power at the line frequencies, but there is no longer any artifact and it looks pretty good overall.

At some point, I may try downsampling and reinstating the chunking. I will let you know if I do, and how it went. 

Thanks again!

**Comment by gwfolk** [comment]
Since it looks as if Zapline-Plus is adding power to a broad range of frequencies within certain time chunks, I'm wondering if this artifact could be related to these large negative "total power removed" values that confused me a while back? Notice how a large part of the spectrum is shifted up in this example (blue line and arrow added for visualization).

![Zapline-Plus RemovingNegativePower](https://github.com/MariusKlug/zapline-plus/assets/88571666/4873f6bf-adb7-4228-b6a5-9a1d73347ba9)

Your last figure still looks like power might have been added somehow, but since the whole thing was treated as one 'chunk', it makes sense that there wouldn't be visible vertical lines. Are the top and bottom spectrograms color-scaled the same?

Edit for context: this is a two-hour recording from a 32-channel probe in mouse barrel cortex. Their whiskers are flicked at 20 Hz in ~1000 trials, 500 ms each.

**Comment by elsahh** [comment]
> Since it looks as if Zapline-Plus is adding power to a broad range of frequencies within certain time chunks, I'm wondering if this artifact could be related to these large negative "total power removed" values that confused me a while back? Notice how a large part of the spectrum is shifted up in this example (blue line and arrow added for visualization).
> 
> ![Zapline-Plus RemovingNegativePower](https://user-images.githubusercontent.com/88571666/245301407-4873f6bf-adb7-4228-b6a5-9a1d73347ba9.png)
> 
> Your last figure still looks like power might have been added somehow, but since the whole thing was treated as one 'chunk', it makes sense that there wouldn't be visible vertical lines. Are the top and bottom spectrograms color-scaled the same?
> 
> Edit for context: this is a two-hour recording from a 32-channel probe in mouse barrel cortex. Their whiskers are flicked at 20 Hz in ~1000 trials, 500 ms each.

Hi, I was wondering if you found a solution to prevent this broadband power increase after noise removal?

Best,
Elsa

**Comment by MariusKlug** [comment]
This can happen if the wrong frequency is detected or if the noise power is particularly high. In the above screenshot by @GrantFolkert it detected a non-line frequency, so in that case I'd suspect it would work much better if the frequency is manually chosen.

Do you have the same issue?

**Comment by elsahh** [comment]
> This can happen if the wrong frequency is detected or if the noise power is particularly high. In the above screenshot by @GrantFolkert it detected a non-line frequency, so in that case I'd suspect it would work much better if the frequency is manually chosen.
> 
> Do you have the same issue?

Thank you for your quick answer! Yes, I am facing the same problem. In one recording, Zapline detects some non-line frequency, resulting in broadband power increase, (fig. 1) while it seems to work well for line frequencies (fig. 2). 

![zapline](https://github.com/MariusKlug/zapline-plus/assets/80045974/d7637ab4-4068-41ed-a1e2-963e2c7d2513)

![zapline2](https://github.com/MariusKlug/zapline-plus/assets/80045974/55a51ed7-6b1b-4ddf-8d49-8755bcd257cc)

Beyond that, Zapline also detects frequencies, which seem like non-line frequencies to me, but it removes it well:

![zapline3](https://github.com/MariusKlug/zapline-plus/assets/80045974/df9eb69b-b379-4fb4-9229-53b03bf757a4)

In another recording, Zapline increases broadband power even for a line noise frequency:

![zapline4](https://github.com/MariusKlug/zapline-plus/assets/80045974/1de1b4a2-a738-4580-86f0-48d622080777)

Please note that my data has stimulation artifacts at 160 Hz (+ harmonics), which I am not trying to remove in this step. My data has a high sampling rate, so I tried downsampling it which had no effect on performance. As you suggested, I would assume that specifying the frequencies beforehand would lead to a much better performance, but the last figure seems to contradict that?

Thank you very much in advance!

**Comment by MariusKlug** [comment]
Hmm it removes a lot of components, that is odd. It seems like the spatial filter can't easily dissect the signal. Maybe it would be a good start to manually use 60 and 160hz as noise freqs and set the number of components to remove to something between 5 and 10 manually. Unfortunately this isn't an exact science, sorry :D

**Comment by elsahh** [comment]
> Hmm it removes a lot of components, that is odd. It seems like the spatial filter can't easily dissect the signal. Maybe it would be a good start to manually use 60 and 160hz as noise freqs and set the number of components to remove to something between 5 and 10 manually. Unfortunately this isn't an exact science, sorry :D

So, what helped in the end was 1) specifying the noise frequency, 2) cropping the recording and leaving only the part essential for analysis, 3) excluding any bad channels, and 4) high pass filtering before and not after Zapline. Setting the number of components to a specific number unfortunately led to weak cleaning. Thanks for your help!

**Comment by MariusKlug** [comment]
Glad to hear you found a way to make it work!
