### ISSUE TITLE
find_next_noisefreq argument out to fix

### ISSUE THREAD

**Issue by CPernet** [MariusKlug/zapline-plus#4]
not specifying the line freq. noise, can occasionally (ie in some subjects - haven't check why) , lead to this error:
'Error using clean_data_with_zapline_plus (line 807)
Output argument "thisfreqs" (and maybe others) not assigned during call to "find_next_noisefreq".'

(ran on linux/matlan2019b)

**Comment by MariusKlug** [comment]
thanks, will check!

**Comment by MariusKlug** [comment]
hmm are you sure you used the latest version of zap+? i do not even have a "thisfreqs" variable in the code anymore...

**Comment by CPernet** [comment]
it came out from running  clean_data_with_zapline_plus (line 807)  - yep from the last update

**Comment by MariusKlug** [comment]
ah i see, i think i found it. pushed a new version right now, lets see!
