### ISSUE TITLE
EEG.etc.zapline requires lot's of disk space

### ISSUE THREAD

**Issue by behinger** [MariusKlug/zapline-plus#6]
I was wondering why my .set files are so large, zapline saves the raw spectrum for all channels, actually twice:
![grafik](https://user-images.githubusercontent.com/10183650/151968543-9d28aa75-8952-44f8-a89e-47e2d45255ac.png)

Maybe make this optional and off by default?

**Comment by MariusKlug** [comment]
Hmm, yes that is probably a good idea! We used it for our plots and I like to give full information on everything but yes probably that is overkill for the everyday user. Will adapt!

**Comment by MariusKlug** [comment]
pushed new update :)
